# Generated by Django 5.0.4 on 2024-05-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0002_rating_datetime_alter_rating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='name',
            field=models.CharField(default='Barr', max_length=1000),
            preserve_default=False,
        ),
    ]
