# Generated by Django 5.0.4 on 2024-05-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0004_alter_rating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='img',
            field=models.CharField(default='Hey', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='release',
            field=models.CharField(default='hey', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='rated_by', to='rater.rating'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saved_albums',
            field=models.ManyToManyField(blank=True, related_name='album_saved_by', to='rater.album'),
        ),
    ]
