# Generated by Django 5.0.4 on 2024-05-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0005_album_img_album_release_user_ratings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='liked_ratings',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='rater.rating'),
        ),
    ]
