# Generated by Django 5.0.4 on 2024-05-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0007_remove_user_followers_remove_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='notes',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='rating',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
