# Generated by Django 5.0.4 on 2024-05-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0009_rename_notes_rating_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.CharField(default='Boo', max_length=100),
            preserve_default=False,
        ),
    ]
